url: https://codinginspiration.com
baseurl: '/cdi2016.github.io'

# Site settings
title: Coding Inspiration
email: cdi2016.fpt@gmail.com
description: "Chủ đề Game on! Japan - Game hóa Nhật Bản"


# Team names, titles and social links
people:
- name: Thầy Đào Trọng Duy
  pic: 1
  position: Trưởng phòng đào tạo - Viện đào tạo quốc tế FPT
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Thầy Chu Tuấn Luyện
  pic: 2
  position: Giảng viên bộ môn lập trình - ĐH FPT
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/Quanduirach?fref=ts
    - title: linkedin
      url: https://vn.linkedin.com/in/luyenchu

- name: Cô Lại Xuân Thu
  pic: 3
  position: Giảng viên bộ môn tiếng Nhật - ĐH FPT
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/haru.aki.10?fref=ts
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
